server:
  port: 9000

spring:
  main:
    allow-bean-definition-overriding: true

vds:
  jwt:
    location: classpath:vds.jks
    alias: vds
    password: ty70432159
    tokenTTL: 7d
  auth:
    excludePaths:
      - /register/**
      - /register
      - /login/**
      - /login
      - /brands/**
      - /models/**
      - /cars/**
      - /evaluates/**
      - /parkades/**
    includePaths:
      - /users/**
      - POST::/evaluates/reply
      - /coupons/**
      - /couponUsers/**
      - /messages/**
      - /orders/**
      - /pays/**
