vds:
  mysql:
    host: 192.168.49.128
    port: 3306
    database: vehicle_dispatch
    username: root
    password: ty70432159
  redis:
    host: 192.168.49.128
    port: 6379
    password: ty70432159
  nacos:
    host: 192.168.49.128
    port: 8848
  sentinel:
    host: 192.168.49.128
    port: 8858
  swagger:
    title: 校园租车系统用户支付接口文档
    description: "校园租车系统用户支付接口文档"
    email: 164354971@qq.com
    concat: 田园
    package: cn.lingbaocrisps.user.controller
